// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kvzdthectysaccchpild.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt2emR0aGVjdHlzYWNjY2hwaWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYxMDcwNzIsImV4cCI6MjEwMTY4MzA3Mn0.jEJOXCGKTmo1d5DNs2kRSkLXoFrktDR5aCPZ_239F40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});