// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieexucxbbpfudeedehva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllZXh1Y3hiYnBmdWRlZWRlaHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ1ODc1MDYsImV4cCI6MjEwMDE2MzUwNn0.ErfJSyewbP2QpR7O8UOxfx2PsoNgGIOjSw0FUJVzNNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});